### ISSUE TITLE
add a prettier file for code formatting consistency [documentation]

### ISSUE THREAD

**Issue by VanWeapon** [jmir1/osm#10]
Code formatting is an annoying thing that shows up in the PRs and is unnecessary noise, would recommend adding a .prettierrc file to the project to make sure the same settings are being used by all contributors for things like tabwidth and wrapping width

**Comment by jmir1** [comment]
https://github.com/jmir1/osm/commit/e73bb145e36296e2017eded4fb87a7840a1ffd0b
you can also change this file if you want, i dont really care
