### ISSUE TITLE
Include profile id in the /rankings response

### ISSUE THREAD

**Issue by VanWeapon** [jmir1/osm#6]
This allows subsequent re-calling of the API to endpoints requiring a user id, such as `/stock` using data fetched from leaderboard

**Comment by jmir1** [comment]
yes I also planned to add this already, I saw in your react app you had a link to the osu profile instead of the /stock thing

**Comment by jmir1** [comment]
Done in https://github.com/jmir1/osu-stocks/commit/7c34c8cfa96bb4cd4b5028ba002ec18ae0872e51
